sudo: required
language: node_js
node_js:
  - "7.0"

before_install:
  - "curl -L https://git.io/ejPSng | /bin/sh"
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"

before_script:
  - "export PATH=$HOME/.meteor:$PATH"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - meteor test-packages ./ --driver-package dispatch:mocha-phantomjs
